### ISSUE TITLE
动态加文本没反应

### ISSUE THREAD

**Issue by JackyChan** [yyued/SVGAPlayer-Flutter#10]
使用dynamicItem.setText设置动态文本没有任何效果，请问是什么原因？key对应正确。

**Comment by PonyCui** [comment]
提供可复现的 Demo 看看

**Comment by JackyChan** [comment]
[redpacket_open.svga.zip](https://github.com/yyued/SVGAPlayer-Flutter/files/3858911/redpacket_open.svga.zip)

不好意思，之前赶项目，没时间来跟进，这是我们使用的svga文件，不知道是不是生成的svga文件有问题，使用你们提供的示例文件是可以设置文本的，但是我们自己生成的就无法设置文本。

**Comment by PonyCui** [comment]
可以提供一个 Demo 工程吗？提供 zip 包或者 git repo 都可以。

**Comment by JackyChan** [comment]
好的，上传了一个demo

[svga_demo.zip](https://github.com/yyued/SVGAPlayer-Flutter/files/3893113/svga_demo.zip)

**Comment by PonyCui** [comment]
Fixed https://github.com/yyued/SVGAPlayer-Flutter/commit/3a37133e9e43d7798c320ec8ed76e9dd6d7b9b7a
Please use 1.0.1
