### ISSUE TITLE
trim path issue!

### ISSUE THREAD

**Issue by Hassan-Fa** [yyued/SVGAPlayer-Flutter#13]
this simple **individually** trimming path (ae preview):
![Comp 1_1](https://user-images.githubusercontent.com/39556293/67092962-737a0400-f1bd-11e9-9f89-d485cc305563.gif)

is rendered like this (containing svga file):
[test5.zip](https://github.com/yyued/SVGAPlayer-Flutter/files/3743778/test5.zip)

help me out here ❤️ 
thanks

**Comment by Hassan-Fa** [comment]
@errnull could we expect a fix soon my friend ??
only straight lines are getting trimPathed correctly
is there anything i could do so that it'll render fine?
❤️

**Comment by PonyCui** [comment]
Could you provide the sample aep file?

**Comment by Hassan-Fa** [comment]
here
[test1.zip](https://github.com/yyued/SVGAPlayer-Flutter/files/3747640/test1.zip)

**Comment by errnull** [comment]
Hello, you could upgrade the SVGA AE Converter to fix it.
[SVGAConverter_AE.zxp.zip](https://github.com/yyued/SVGAPlayer-Flutter/files/3748976/SVGAConverter_AE.zxp.zip)
@Hassan-Fa

**Comment by Hassan-Fa** [comment]
yes it's resolved indeed :)

thank you ❤️
