### ISSUE TITLE
Unable to load asset

### ISSUE THREAD

**Issue by Hassan-Fa** [yyued/SVGAPlayer-Flutter#14]
tried implementing the exported svga file like this :

`SVGASimpleImage(assetsName: "assets/svga/first_card.svga")`

animation didn't load and got this : 

`E/flutter (12135): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Unable to load asset: assets/svga/first_card.svga`
`E/flutter (12135): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:230:7)`
`E/flutter (12135): <asynchronous suspension>`
`E/flutter (12135): #1      SVGAParser.decodeFromAssets` `(package:svgaplayer_flutter/parser.dart:18:52)
E/flutter (12135): <asynchronous suspension>`
`E/flutter (12135): #2      new _SVGASimpleImageState (package:svgaplayer_flutter/simple_player.dart:28:25)`
`E/flutter (12135): #3      SVGASimpleImage.createState (package:svgaplayer_flutter/simple_player.dart:11:12)`
`E/flutter (12135): #4      new StatefulElement (package:flutter/src/widgets/framework.dart:4041:25)`
`E/flutter (12135): #5      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:802:38)`
`E/flutter (12135): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3104:40)`
`E/flutter (12135): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)`
`E/flutter (12135): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)`
`E/flutter (12135): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)`
`E/flutter (12135): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)`
`E/flutter (12135): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)`
`E/flutter (12135): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)`
`E/flutter (12135): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)`
`E/flutter (12135): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)`
`E/flutter (12135): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)`
`E/flutter (12135): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)`
`E/flutter (12135): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)`
`E/flutter (12135): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)`
`E/flutter (12135): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)`
`E/flutter (12135): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)`
`E/flutter (12135): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)`
`E/flutter (12135): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)`
`E/flutter (12135): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)`
`E/flutter (12135): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)`
`E/flutter (12135): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)`
`E/flutter (12135): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4111:11)`
`E/flutter (12135): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)`
`E/flutter (12135): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)`
`E/flutter (12135): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)`
`E/flutter (12135): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)`
`E/flutter (12135): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)`
`E/flutter (12135): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)`
`E/flutter (12135): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)`
`E/flutter (12135): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)`
`E/flutter (12135): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)`
`E/flutter (12135): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)`

didn't find anything else about how to properly implement everything
did i miss sth ?

**Comment by PonyCui** [comment]
Provide a demo.

**Comment by Hassan-Fa** [comment]
my bad
seems I was too tired last night to remember to add the new folder I created in assets folder in the pubsec file as the new assets directory

🙏 ❤️
