### ISSUE TITLE
too heavy animation

### ISSUE THREAD

**Issue by Hassan-Fa** [yyued/SVGAPlayer-Flutter#15]
just tested my first svga file and it's causing the app to almost crash , many frames are lost ( app frames , not just the animation )

recorded on real device ( although recording caused it to be worse but it was pretty much the same even not recording it ) :

[mobizen_20191107_151653.zip](https://github.com/yyued/SVGAPlayer-Flutter/files/3819445/mobizen_20191107_151653.zip)

and this is the svga file : 

[first_card.zip](https://github.com/yyued/SVGAPlayer-Flutter/files/3819449/first_card.zip)

is this the current normal ?

**Comment by PonyCui** [comment]
Use png (bitmap) replace vector.

**Comment by Hassan-Fa** [comment]
you mean in the after effects I should export vectors to png and replace them ?

**Comment by Hassan-Fa** [comment]
@PonyCui you mean in the after effects I should export vectors to png and replace them ?

**Comment by PonyCui** [comment]
Use png instead of vector in AE if possible.
