### ISSUE TITLE
AE2020 无法正常导出

### ISSUE THREAD

**Issue by HiCatcat** [yyued/SVGAPlayer-Flutter#16]
更新了AE2020后，svga导出时会提示「将不写入渲染日志」「无法转换Unicode字符」

**Comment by HiCatcat** [comment]
> 更新了AE2020后，svga更新时会提示“将不写入渲染日志”“无法转换Unicode字符”

**Comment by errnull** [comment]
即将支持，
关注一下 https://github.com/svga/SVGA-AEConverter/issues/11
