### ISSUE TITLE
protobuf version conflict

### ISSUE THREAD

**Issue by hcoderLee** [yyued/SVGAPlayer-Flutter#17]
My project is using protobuf ^1.0.0 which is higher than your version. When I rollback to ^0.13.4, tons of error happened in proto generated dart file. I have checked the release message of dart protobuf and the 1.0.0 is released in the same month with 0.13, so I think you should update the protobuf version.

**Comment by PonyCui** [comment]
Agreed, I will update soon.

**Comment by PonyCui** [comment]
1.0.0 released, use the latest version of protobuf.
