### ISSUE TITLE
部分动画出不来

### ISSUE THREAD

**Issue by TaleAi** [yyued/SVGAPlayer-Flutter#2]
painter.dart中的变换会导致部分图片出不来，改为如下可以正常显示
`if(frameItem.hasTransform()) {
        canvas.transform(Float64List.fromList([
          frameItem.transform.a,
          frameItem.transform.b,
          0.0,
          0.0,
          frameItem.transform.c,
          frameItem.transform.d,
          0.0,
          0.0,
          0.0,
          0.0,
          1.0,
          0.0,
          frameItem.transform.tx,
          frameItem.transform.ty,
          0.0,
          1.0
        ].toList()));
      }`

**Comment by TaleAi** [comment]
测试动画https://kk-oss-bucket.oss-cn-shanghai.aliyuncs.com/file/gift/yh.svga

**Comment by PonyCui** [comment]
感谢指正，已经提交修复代码。
