### ISSUE TITLE
_SVGASimpleImageState#daa48(ticker active) was disposed with an active Ticker

### ISSUE THREAD

**Issue by Hassan-Fa** [yyued/SVGAPlayer-Flutter#20]
I'm using svga animations in a pageView
and it seems like the ticker is leaking
where or how should I dispose it ?

should I be asking these question on stackoverflow ?
this looks to be a better place to ask you directly

**Comment by wbbbbbbbbbbbbbbbbbb** [comment]
hey man,He doesn't use the destroy function in svgasimpleimage, just the way you use the controller

**Comment by wbbbbbbbbbbbbbbbbbb** [comment]
use SVGAImage can ok
