### ISSUE TITLE
两个svga持续播放的时候内存会一致往上走

### ISSUE THREAD

**Issue by wuzaozhou** [yyued/SVGAPlayer-Flutter#27]

**Comment by wuzaozhou** [comment]
后天每6 s下发一次svga播放，且同时播放两个svga，长时间之后内存会往上走，从最初的320到700+，使用RepaintBoundary包裹custompaint 内存上有所优化

**Comment by PonyCui** [comment]
有没有在适当的时候调用 animationController.dispose() ?

**Comment by wuzaozhou** [comment]
> 有没有在适当的时候调用 animationController.dispose() ?

有的，widget销毁的时候会调用animationController.dispose()

**Comment by PonyCui** [comment]
可以提供 Demo 以及对应的测试数据吗？

**Comment by wuzaozhou** [comment]
> 可以提供 Demo 以及对应的测试数据吗？

抱歉，现在没时间弄demo，在公司的项目中的。

昨天还出现一种情况就是内存700M+，后台停止下发，本地svga停止播放之后过一段时间内存能降到400M+，然后后台继续下发，刚播放第一次svga内存立刻飙到700M+

**Comment by wuzaozhou** [comment]
![image](https://user-images.githubusercontent.com/28749288/76846154-060cf500-687b-11ea-995d-8d8e97ceae8e.png)
这是Android上的内存变化

**Comment by wuzaozhou** [comment]
添加每次播放暂停1s在播放下一次，在OPPO R15上还相对比价稳定，在三星S8还是有上升趋势
![image](https://user-images.githubusercontent.com/28749288/76858644-ceaa4280-6892-11ea-99e9-c5d93fdcc4aa.png)
![image](https://user-images.githubusercontent.com/28749288/76858659-d669e700-6892-11ea-9bd1-c0f562544f83.png)

**Comment by PonyCui** [comment]
https://github.com/svga/SVGAPlayer-Flutter#reuse-movieentity
可以使用 2.1.0 版本测试看是否解决问题
