### ISSUE TITLE
shape layer with transparent stroke causing errors

### ISSUE THREAD

**Issue by HustLion** [yyued/SVGAPlayer-Flutter#3]
![image](https://user-images.githubusercontent.com/12825646/57744497-06d57780-76fc-11e9-827b-a8d5b1283001.png)

```
Another exception was thrown: The SVGAPainter#df55c() custom painter called canvas.save() or canvas.saveLayer() at least 1 more time than it called canvas.restore().
```

**Comment by PonyCui** [comment]
Could you provide a sample svga file?

**Comment by HustLion** [comment]
Here is a sample:

[state.zip](https://github.com/yyued/SVGAPlayer-Flutter/files/3181067/state.zip)
