### ISSUE TITLE
什么时候可以增加flutter新版本的支持？

### ISSUE THREAD

**Issue by jasoncfpl** [yyued/SVGAPlayer-Flutter#31]
现在有计划要升级flutter新版本嘛

**Comment by PonyCui** [comment]
并没有限制 Flutter 版本哦

**Comment by jasoncfpl** [comment]
我们这边目前有一个提示，您方便帮忙看一下嘛，我们目前使用的flutter版本是1.17.2
The plugin `svgaplayer_flutter` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.

**Comment by jasoncfpl** [comment]
https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration @PonyCui

**Comment by PonyCui** [comment]
已经在最新的 commit 移除 Native Plugin。

**Comment by jasoncfpl** [comment]
感谢
