### ISSUE TITLE
使用svga播放礼物动画，发现内存暴涨的可怕

### ISSUE THREAD

**Issue by jerrykill** [yyued/SVGAPlayer-Flutter#33]
我们有连送的需求，所以会连续播放多个SVGA动画，观察发现内存暴涨，而且渲染也会卡顿。SVGA是不是再生成的时候就要注意运行内存，然后如果降低运行内存，但是多个同时运行还是会出现内存暴涨的情况。这时候低性能手机就会出现OOM的崩溃。请问有什么思路或者方法可以尽量避免吗？再不改动原有逻辑需求的情况下

**Comment by mojito-droid** [comment]
@jerrykill 请问解决了吗

**Comment by jerrykill** [comment]
> @jerrykill 请问解决了吗
没有解决，最后选择了通过PlatformView使用原生SVGA播放。原生SVGA播放内存释放及时，但是内存要求有点高。最优方案原生调用网页SVGA播放。

**Comment by PonyCui** [comment]
https://github.com/svga/SVGAPlayer-Flutter#reuse-movieentity
可以使用 2.1.0 版本测试看是否解决问题
