### ISSUE TITLE
多个svga内存暴涨，并且是释放不干净

### ISSUE THREAD

**Issue by baofei12** [yyued/SVGAPlayer-Flutter#34]
多个svga内存暴涨，并且是释放不干净，重复关闭又打开，内存一直往上走，直到oom

**Comment by 972223177** [comment]
+1.

**Comment by PonyCui** [comment]
https://github.com/svga/SVGAPlayer-Flutter#reuse-movieentity
可以使用 2.1.0 版本测试看是否解决问题
