### ISSUE TITLE
我们使用了SVGASimpleImage播放动画，导致了发热严重

### ISSUE THREAD

**Issue by EchoPuda** [yyued/SVGAPlayer-Flutter#40]
单纯的使用了SVGASimpleImage.asset进行某个动画的循环播放，但是导致了ios，Android（三星尤其）发热严重，这个主要是什么原因导致的呢，可以优化么？

不管是复杂的还是简单的都会有这个问题

**Comment by ymback** [comment]
请问你最后怎么处理的

**Comment by EchoPuda** [comment]
@ymback 我这主要是跟`PlatformView`一起使用会有问题，会一直频繁的绘制，然后就发热了。现在用`Texture`了。
