### ISSUE TITLE
能不能出一个好一点的API文档

### ISSUE THREAD

**Issue by zboboan** [yyued/SVGAPlayer-Flutter#48]
希望有一个好一点的API的文档，参数，事件，方法，有例子，这前看着才专业

**Comment by PonyCui** [comment]
这跟 Flutter AnimationController 基本一致，可以先学习一下 AnimationController 的 API，也有四个例子提供参考，有不明白的地方稍微阅读一下源码就可以。

https://github.com/svga/SVGAPlayer-Flutter/blob/master/README.zh.md
