### ISSUE TITLE
快速切换SVGA问题

### ISSUE THREAD

**Issue by Iridescentangle** [yyued/SVGAPlayer-Flutter#52]
场景为头像框预览，对应地，设置一个SVGASimpleImage，传入不同的svgaUrl来实现快速切换,
或者模仿SVGASimpleImage的实现方式，通过动态切换解析svga资源来替换controller的videoItem。
目前出现切换失灵的问题，解析之后替换，但svga动画没有按照预期展示

`class SVGAView extends StatefulWidget {
  final String svgaUrl;

  SVGAView(this.svgaUrl);

  @override
  _SVGAViewState createState() => _SVGAViewState();
}

class _SVGAViewState extends State<SVGAView> with TickerProviderStateMixin {
  SVGAAnimationController _controller;

  @override
  void initState() {
    super.initState();
    _controller = SVGAAnimationController(vsync: this);
  }

  @override
  Widget build(BuildContext context) {
    prepareForPlay();
    return SVGAImage(
      _controller,
      fit: BoxFit.fill,
    );
  }

  void prepareForPlay() async {
    MovieEntity entity = await SVGAParser.shared.decodeFromURL(widget.svgaUrl);
    if (entity != null) {
      print(widget.svgaUrl);
      _controller.videoItem = entity;
      _controller.repeat();
    }
  }

  @override
  void dispose() {
    _controller.stop(canceled: true);
    _controller.videoItem = null;
    _controller.dispose();
    super.dispose();
  }
}`
将prepareForPlay在initState中调用有类似的问题，所以改在build中调用

**Comment by Iridescentangle** [comment]
在提供给SVGASimpleImage一个对应的UniqueKey之后，动态SVGA切换成功了，但静态的SVGA仍然在切换后不展示
提供示例svga文件作为参考
https://cowtransfer.com/s/8f97148581ad47
取件码：813651（24小时内有效）
btw，code use中的angle在切换逻辑下是正常的,提供的这两个静态文件会出现此类问题

**Comment by PonyCui** [comment]
可以提交一份可重现问题的代码吗

**Comment by Iridescentangle** [comment]
OK 由于没有外网svga链接,所以将svga放在assets/svga目录下,也能复现
https://cowtransfer.com/s/821f5eec9a3a42
code:234330

**Comment by PonyCui** [comment]
已发布新版本 2.1.0，可以尝试一下是否解决问题，如果问题没有解决，可以重开该 issue。
