### ISSUE TITLE
Upgrade version of http dependencies from ^0.12.2 to ^0.13.0

### ISSUE THREAD

**Issue by XuanTung95** [yyued/SVGAPlayer-Flutter#53]
- Current version is http: ^0.12.2.
- Newest version is http: ^0.13.0, available from Feb 5, 2021
- Could you please upgrade to the newest http version?

**Comment by rainver** [comment]
same issue

**Comment by PonyCui** [comment]
https://pub.dev/packages/svgaplayer_flutter/versions/2.0.0-nullsafety.0
