### ISSUE TITLE
该组件跟dio4.0.0网络请求组件依赖冲突，能否尽快升级一下该组件依赖库到最新版本呢？

### ISSUE THREAD

**Issue by 891806797** [yyued/SVGAPlayer-Flutter#57]
Because no versions of dio match >4.0.0 <5.0.0 and dio 4.0.0 depends on http_parser ^4.0.0, dio ^4.0.0 requires http_parser ^4.0.0.
And because svgaplayer_flutter >=1.2.0 <2.0.0-nullsafety.0 depends on http ^0.12.2 which depends on http_parser >=0.0.1 <4.0.0, dio ^4.0.0 is incompatible with svgaplayer_flutter >=1.2.0 <2.0.0-nullsafety.0.
So, because creamchat depends on both svgaplayer_flutter ^1.2.0 and dio ^4.0.0, version solving failed.
pub get failed (1; So, because creamchat depends on both svgaplayer_flutter ^1.2.0 and dio ^4.0.0, version solving failed.)

**Comment by PonyCui** [comment]
Use 2.0.0
