### ISSUE TITLE
动画覆盖后， 不能交互遮盖的widget？

### ISSUE THREAD

**Issue by CivelXu** [yyued/SVGAPlayer-Flutter#58]
如题

**Comment by PonyCui** [comment]
可以具体描述一下问题吗？

**Comment by CivelXu** [comment]
> 可以具体描述一下问题吗？

svga的动画 会覆盖 整个屏幕用来展示。屏幕下的手势交互 无法传递下去。

**Comment by PonyCui** [comment]
https://github.com/svga/SVGAPlayer-Flutter/commit/a6e4b1bf354eb3b503868cdedec78f008ca597ad
Fixed at commit.

**Comment by PonyCui** [comment]
已发布新版本 2.1.0
