### ISSUE TITLE
SVGAPainter buildDPath解析科学计数法数值出错

### ISSUE THREAD

**Issue by axen1314** [yyued/SVGAPlayer-Flutter#59]
版本：v2.0.0
播放SVGA动画时，出现RangeError (index): Invalid value: Not in inclusive range 0..1: 2错误
![image](https://user-images.githubusercontent.com/25617051/121628165-4e7d8780-caab-11eb-89f0-8c2687d868e1.png)
定位错误出现SVGAPainter buildDPath方法上，结合源码和SVGA数据分析后发现，buildDPath在解析带有科学计数法的数值时会出错，原因出现在下面这行代码中:
![image](https://user-images.githubusercontent.com/25617051/121628116-39085d80-caab-11eb-900c-8ee745e9978c.png)
`
上面这段正则表达式的作用是解析SVGA DPath的数据，分析可以得出结论，当解析带有科学计数法的数值时，数值后的e会被"|||"截掉。下面是一段带有科学计数法数值的SVGA的DPath数据：
`
M340.262 2.842e-14 C340.262 2.842e-14 161.700 2.842e-14 161.700 2.842e-14 C147.387 2.842e-14 136.762 9.937 136.762 24 C136.762 24 136.762 256.687 136.762 256.687 C136.762 271 149.387 282 160.524 282 C160.524 282 340.450 282 340.450 282 C353.387 282 364.762 270.062 364.762 258.937 C364.762 258.937 364.762 23 364.762 23 C364.762 11.954 353.762 2.842e-14 340.262 2.842e-14 Z
`
通过上面的代码解析后，得到下面的内容：
`
|||M 340.262 2.842|||e -14 |||C 340.262 2.842|||e -14 161.700 2.842|||e -14 161.700 2.842|||e -14 |||C 147.387 2.842|||e -14 136.762 9.937 136.762 24 |||C 136.762 24 136.762 256.687 136.762 256.687 |||C 136.762 271 149.387 282 160.524 282 |||C 160.524 282 340.450 282 340.450 282 |||C 353.387 282 364.762 270.062 364.762 258.937 |||C 364.762 258.937 364.762 23 364.762 23 |||C 364.762 11.954 353.762 2.842|||e -14 340.262 2.842|||e -14 |||Z 
`
**可以看到带有科学计数法的数值都被截断了，所有没办法正确解析数据了**，请官方尽快修复这个问题。

**Comment by PonyCui** [comment]
https://github.com/svga/SVGAPlayer-Flutter/issues/60
和这个问题一致的，先关闭，可以继续讨论上述问题。
