### ISSUE TITLE
辛苦大佬帮看下，master分支最新代码，网页预览正常，手机上播放svga异常

### ISSUE THREAD

**Issue by LinAndroid** [yyued/SVGAPlayer-Flutter#62]
本地环境：
Flutter 2.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision adc687823a (2 months ago) • 2021-04-16 09:40:20 -0700
Engine • revision b09f014e96
Tools • Dart 2.12.3

测试手机:
华为mate20 ---- android10 

demo:https://github.com/LinAndroid/SVGAPlayer-Flutter-master

**Comment by PonyCui** [comment]
Fixed at https://github.com/svga/SVGAPlayer-Flutter/commit/ab0894f794331fa354172f08f0094cc1ab10ff37
Upgrade version to 2.1.2
感谢反馈
