### ISSUE TITLE
2.1.2版本播放svga偶现异常

### ISSUE THREAD

**Issue by LinAndroid** [yyued/SVGAPlayer-Flutter#63]
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
'dart:ui/painting.dart': Failed assertion: line 1634 pos 12: '<optimized out>': is not true.

When the exception was thrown, this was the stack: 
#2      Image.dispose (dart:ui/painting.dart:1634:12)
#3      MovieEntity.dispose.<anonymous closure> (package:svgaplayer_flutter/proto/svga.pb.dart:1775:15)
#4      Iterable.forEach (dart:core/iterable.dart:257:30)
#5      MovieEntity.dispose (package:svgaplayer_flutter/proto/svga.pb.dart:1774:24)
#6      SVGAAnimationController.videoItem= (package:svgaplayer_flutter/player.dart:53:24)
...
====================================================================================================

本地环境：
Flutter 2.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision adc687823a (2 months ago) • 2021-04-16 09:40:20 -0700
Engine • revision b09f014e96
Tools • Dart 2.12.3

demo:暂无

测试手机:vivo X21i A.         系统版本:Android 9

**Comment by PonyCui** [comment]
请具体说明重现步骤

**Comment by LinAndroid** [comment]
确定是多次调用movieentity的dispose的问题，
