### ISSUE TITLE
最新代码，点击svga所在容器，ontap事件无法响应

### ISSUE THREAD

**Issue by LinAndroid** [yyued/SVGAPlayer-Flutter#64]
demo :https://github.com/LinAndroid/SVGAPlayer-Flutter-master

本地环境：
Flutter 2.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision adc687823a (2 months ago) • 2021-04-16 09:40:20 -0700
Engine • revision b09f014e96
Tools • Dart 2.12.3

测试手机：vivo x21i a       android 9

**Comment by LinAndroid** [comment]
测试过程中发现给container设置color后可响应

**Comment by PonyCui** [comment]
GestureDetector 包裹的 Container， onTap 是必须设置 color 才能响应的，这个不是 SVGAPlayer 的问题，是 Flutter 本身的问题。

**Comment by LinAndroid** [comment]
谢谢大佬，demo已更新。在demo中，去掉container层级，这种写法，依然会无法响应ontap事件，这个会是svgplayer的问题吗？：
GestureDetector(
          onTap: () {
                      print("哈哈哈哈哈哈哈哈哈哈");
          },
          // child: Container(
           //   color: Colors.transparent,
           child: SVGAImage(this.animationController!),
          // ),
 ))

**Comment by PonyCui** [comment]
不是，SVGAImage 默认不提供任何 Pointer 能力，所以你仍然是需要使用 Container Wrap SVGAImage 才能响应 Gesture.

**Comment by LinAndroid** [comment]
哦，那理解了，谢谢～～

**Comment by SixSheeppp** [comment]
可以给 `GestureDetector`加一个`   behavior: HitTestBehavior.opaque,`也可以解决
