### ISSUE TITLE
2.1.2特殊svga文件显示不了 报bad data

### ISSUE THREAD

**Issue by CarrySniper** [yyued/SVGAPlayer-Flutter#65]
其他的svga文件显示正常，但是我这个文件就有问题，能帮解决一下吗？

原生的SVGAPlayer也显示正常，就是flutter版本的报bad data。

文件地址：http://paopao.cn-gd.ufileos.com/gift/aidejuanzhou/svga.svga

**Comment by PonyCui** [comment]
您当前播放的 SVGA 文件版本为：1.0
SVGAPlayer-Flutter 不支持 1.0，请到 https://svga.io 转换至 2.0 再使用。

**Comment by CarrySniper** [comment]
> 您当前播放的 SVGA 文件版本为：1.0
> SVGAPlayer-Flutter 不支持 1.0，请到 https://svga.io 转换至 2.0 再使用。

好的，感谢指导。已转换解决。
