### ISSUE TITLE
SVGASimpleImage不会刷新

### ISSUE THREAD

**Issue by jipengzheng** [yyued/SVGAPlayer-Flutter#66]
当SVGASimpleImage使用动态的远端url时，动画不会刷新，只有切换到其他页面再回来才会刷新

**Comment by PonyCui** [comment]
提供一个 Demo

**Comment by jipengzheng** [comment]
找到原因了，SVGASimpleImage里面用了controller控制，在initState时做了初始化处理，所以如果页面只是重新build，没有重新加载，controller没有改变，动画不会刷新。已经采用其他方式规避。
