### ISSUE TITLE
svga cash

### ISSUE THREAD

**Issue by abdokamal25** [yyued/SVGAPlayer-Flutter#69]
I cached svga image by Dio package and I could to get the path, but how can I show this image from the cached path into SVGASimpleImage widget

`Ex: path = ‘’/data/user/0/com.room_app/app_flutter/picture.svga”`

how to make my svga work from this path
and i want for example, how to use this
`SVGAParser.decodeFromBytes`

**Comment by PonyCui** [comment]
https://github.com/svga/SVGAPlayer-Flutter#code-to-use
