### ISSUE TITLE
iPhone 12 真机 Crash

### ISSUE THREAD

**Issue by DizzyDuan** [yyued/SVGAPlayer-Flutter#71]
svgaplayer_flutter: 2.1.2

iPhone 12 真机
svga文件大小：915KB
同时播放4个

[svga_example.zip](https://github.com/svga/SVGAPlayer-Flutter/files/7930514/svga_example.zip)

name = 'io.flutter.1.io', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=2098 MB, unused=0x0)
    frame #0: 0x00000001046421b8 Flutter`SkMipmap::Build(SkPixmap const&, SkDiscardableMemory* (*)(unsigned long), bool) + 1892
Flutter`SkMipmap::Build:
->  0x1046421b8 <+1892>: str    x9, [x20, #0x8]!
    0x1046421bc <+1896>: str    x13, [x19]
    0x1046421c0 <+1900>: str    xzr, [x19, #0x10]
    0x1046421c4 <+1904>: mov    x9, x19
Target 0: (Runner) stopped.

**Comment by PonyCui** [comment]
请不要使用这种序列帧的方式去设计、导出动画，这样还不如去用 GIF 的，我们在 AE Converter 里面已经警告过设计师了，超出内存限制是会导致应用崩溃的。

**Comment by DizzyDuan** [comment]
@PonyCui 请问怎么可以不用序列帧的方式实现类似的效果?

**Comment by PonyCui** [comment]
@DizzyYang 这不是技术问题
