### ISSUE TITLE
很多web方法怎么实现？

### ISSUE THREAD

**Issue by zboboan** [yyued/SVGAPlayer-Flutter#73]
播放完成后停在首帧，停在尾帧  
顺序播放
倒序播放
循环次数（无限循环）
开始播放的帧数
结束播放的帧数
字体的替换更改
这些web可以实现的方法，在flutter里怎么实现？可不可以出一个文档教教这些方法怎么实现

**Comment by PonyCui** [comment]
https://github.com/svga/SVGAPlayer-Flutter/wiki/Dynamic-Drawer
AnimationController 的 API 参考 Flutter 官方文档
