### ISSUE TITLE
有些方法flutter 不可以实现嘛？

### ISSUE THREAD

**Issue by zboboan** [yyued/SVGAPlayer-Flutter#74]
播放完成后停在首帧
播放完成后停在尾帧
循环次数（无限循环）
开始播放的帧数
结束播放的帧数
文字的编辑
暂停播放动画
继续播放动画
停止播放动画
这些方法flutter 可以实现嘛？

**Comment by orzzp** [comment]
播放完成后停在尾帧
这个我也需要...🙁

**Comment by PonyCui** [comment]
自行通过监听 AnimationController 设置就可以了
