### ISSUE TITLE
部分svga解析出错

### ISSUE THREAD

**Issue by hhyq520** [yyued/SVGAPlayer-Flutter#76]
E/flutter ( 3677): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FormatException: Filter error, bad data
E/flutter ( 3677): #0      _FilterImpl.processed (dart:io-patch/filter_patch.dart:12:69)
E/flutter ( 3677): #1      _FilterSink.addSlice (dart:io/data_transformer.dart:537:29)
E/flutter ( 3677): #2      _FilterSink.add (dart:io/data_transformer.dart:521:5)
E/flutter ( 3677): #3      ZLibDecoder.convert (dart:io/data_transformer.dart:395:9)
E/flutter ( 3677): #4      _ZLibDecoder.decodeBytes (package:archive/src/zlib/_zlib_decoder_io.dart:13:32)
E/flutter ( 3677): #5      ZLibDecoder.decodeBytes (package:archive/src/zlib_decoder.dart:13:32)
E/flutter ( 3677): #6      SVGAParser.decodeFromBuffer (package:svgaplayer_flutter/parser.dart:37:49)
E/flutter ( 3677): #7      SVGAParser.decodeFromAssets (package:svgaplayer_flutter/parser.dart:27:12)
E/flutter ( 3677): <asynchronous suspension>
E/flutter ( 3677): #8      _SvgaImageState._loadAnimation (package:flutter_base_lib/pages/main/widgets/svga_image.dart:34:23)
E/flutter ( 3677): <asynchronous suspension>
在svga 在线预览网址是可以播放的[https://svga.io/svga-preview.html](https://svga.io/svga-preview.html)
播放不了的文件地址：https://github.com/hhyq520/svga

**Comment by PonyCui** [comment]
不支持 1.0 格式的呢，找设计师重新导出一下吧。
