### ISSUE TITLE
svgaplayer_flutter >=2.0.0 depends on path_drawing ^0.5.1

### ISSUE THREAD

**Issue by sayhellotogithub** [yyued/SVGAPlayer-Flutter#77]
svgaplayer_flutter >=2.0.0 depends on path_drawing ^0.5.1

**Comment by SheepYang1993** [comment]
所以这个要怎么解决？ @PonyCui

**Comment by sayhellotogithub** [comment]
在 pubspec，修改path_drawing
` path_drawing: '>=0.5.1 <2.0.0'`

参考  https://dart.dev/tools/pub/dependencies
